import Head from 'next/head';
import HomeC from '@/components/Home';

export default function Home() {
  const a = null
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeC />
      </main>
    </div>
  );
}
