import { useComments } from 'context/comments/useComments';
import Comment from 'components/Comment';
import Head from 'next/head';

export default function Home() {
  const { comments, changeScoreComment } = useComments();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {comments.map((comment, index) => (
          <Comment
            key={index + 'comments'}
            {...comment}
            _handleCLickScore={(type) =>
              changeScoreComment && changeScoreComment(type)
            }
          />
        ))}
      </main>
    </div>
  );
}
