name: "CI Planet"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Run installation
      - uses: actions/checkout@v3
      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
            
      - run: yarn install
      - name: Run linter
      - run: yarn lint
