name: "CI Planet"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Run installation
      - uses: actions/checkout@v3
      
        run: yarn install
      - name: Run linter
        run: yarn lint
